version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - DWA_PROXY_URL=${DWA_PROXY_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev